In [1]:
import pandas as pd
df_nodes = pd.read_csv("output_nodes.csv")
df_nodes.head(5)

    node_id        lat        lon  highway
0  27518751  43.173565  76.479944      NaN
1  27518753  43.174163  76.484691      NaN
2  27518755  43.174727  76.488963      NaN
3  27518757  43.175702  76.494729      NaN
4  27518759  43.176730  76.498596      NaN

In [2]:
df_ways = pd.read_csv("output_ways.csv")
df_ways.head(5)

,way_id,highway,name,oneway,maxspeed_kmh,node_refs
0,4489470,primary,улица Ардагерлер,no,70,1825792054 1825791899 10989365436 7599281823 1...
1,22735404,trunk,Райымбек даңғылы,yes,90,292229172 3208211867 243883410
2,23456586,trunk,NaN,yes,90,243881067 9807865263 3719763539 1389358651 138...
3,23648735,tertiary,улица Маргулана,no,40,2001352125 10290708256 10923154028 9946467977 ...
4,23982247,residential,Дінмұхамед Қонаев көшесі,no,25,3056765533 2817468068 3056765552 2817468076 13...

In [3]:
df_edges = pd.read_csv("output_edges.csv")
df_edges.head(5)

,from_node,to_node,way_id,highway,distance_m,speed_kmh,travel_time_s,oneway
0,1825792054,1825791899,4489470,primary,67.49,70,3.47,no
1,1825791899,1825792054,4489470,primary,67.49,70,3.47,no
2,1825791899,10989365436,4489470,primary,12.29,70,0.63,no
3,10989365436,1825791899,4489470,primary,12.29,70,0.63,no
4,10989365436,7599281823,4489470,primary,3.10,70,0.16,no

In [4]:
df_nodes.describe()

            node_id            lat            lon  highway
count  1.668910e+05  166891.000000  166891.000000      0.0
mean   1.008917e+10      43.203795      76.665664      NaN
std    3.095811e+09       0.041814       0.112919      NaN
min    2.751875e+07      43.009566      76.338617      NaN
25%    1.026828e+10      43.172539      76.572642      NaN
50%    1.099742e+10      43.201016      76.668440      NaN
75%    1.212008e+10      43.236021      76.772458      NaN
max    1.375909e+10      43.322406      76.845468      NaN

In [5]:
df_ways.describe()

             way_id  maxspeed_kmh
count  2.094500e+04  20945.000000
mean   1.074239e+09     22.849224
std    3.612081e+08     11.287648
min    4.489470e+06      2.000000
25%    1.026918e+09     15.000000
50%    1.185075e+09     25.000000
75%    1.313440e+09     30.000000
max    1.503408e+09    120.000000

In [6]:
df_edges.describe()

,from_node,to_node,way_id,distance_m,speed_kmh,travel_time_s
count,3.467320e+05,3.467320e+05,3.467320e+05,346732.000000,346732.000000,346732.000000
mean,1.002416e+10,1.002422e+10,9.954846e+08,22.981308,25.012727,4.235241
std,3.155058e+09,3.154966e+09,3.931546e+08,33.059194,10.811974,7.807870
min,2.751875e+07,2.751875e+07,4.489470e+06,0.040000,2.000000,0.010000
25%,1.024055e+10,1.024055e+10,7.617347e+08,7.690000,15.000000,1.120000
50%,1.099718e+10,1.099718e+10,1.173725e+09,13.440000,30.000000,2.090000
75%,1.211199e+10,1.211199e+10,1.231424e+09,25.630000,30.000000,4.390000
max,1.375909e+10,1.375909e+10,1.503408e+09,1414.260000,120.000000,496.350000

In [10]:
print(f"Number of nodes: {df_nodes.shape}")
print(f"Number of ways: {df_ways.shape}")
print(f"Number of edges: {df_edges.shape}")

Number of nodes: (166891, 4)
Number of ways: (20945, 6)
Number of edges: (346732, 8)